# Generated by Django 5.1.3 on 2024-11-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_man'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man',
            name='girlfriend',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
