# Generated by Django 5.1.3 on 2024-11-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_man_girlfriend'),
    ]

    operations = [
        migrations.AddField(
            model_name='man',
            name='wife',
            field=models.BooleanField(default=False),
        ),
    ]
