# Generated by Django 5.1.3 on 2025-01-11 16:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_man_wife'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='review',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='man',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='man',
            name='girlfriend',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Девушка'),
        ),
        migrations.AlterField(
            model_name='man',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='man',
            name='surname',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='man',
            name='wife',
            field=models.BooleanField(default=False, verbose_name='Жена'),
        ),
    ]
