# Generated by Django 5.1.3 on 2025-01-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_review_alter_man_age_alter_man_girlfriend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
